### ISSUE TITLE
[BUG] When nodes are incorrectly rendered

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#141]
### Describe the Bug

`kaoto-next` render two `when` nodes instead of a single one.

### Steps to Reproduce the Bug or Issue

1. Using the following source code

```yaml
- route:
    id: route-8888
    from:
      uri: timer:tutorial
      steps:
      - set-header:
          simple: "${random(2)}"
          name: my-choice-kebab-cased
      - setHeader:
          simple: "${random(20)}"
          name: myChoiceCamelCased
      - choice:
          when:
          - simple: "${header.myChoice} == 1"
            steps:
            - log:
                id: log-1
                message: We got a one.
          - simple: "${header.myChoice} == 2"
            steps:
            - log:
                id: log-2
                message: We got something else.
          otherwise:
            steps:
            - to:
                uri: 'amqp:queue:'
            - to:
                uri: 'amqp:queue:'
            - log:
                id: log-2
                message: "We got a ${body}"
      - to:
          uri: direct:my-route
          parameters:
            bridgeErrorHandler: true
```

2. Go to the Design Page and see how there are two `when` nodes present

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/c393d810-1518-4ea6-b07a-4e4a5d8a1a25)

### Platform

- OS: [Windows]
- Browser: [Firefox]
