### ISSUE TITLE
Configure KameletBinding & Pipe properties

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#149]
### Context
In continuation of https://github.com/KaotoIO/kaoto-next/issues/74, we need to support configuring `KameletBinding` and `Pipe` properties.

This information is stored in the `Kamelets` catalog definition.

### Goal
Enable configuring properties for `KameletBinding` and `Pipe` properties.

<details>
  <summary>Source code example</summary>
 
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: route-1694
spec:
  source:
    properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: azure-storage-blob-cdc-source
    types: {}
  steps:
  - properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: freemarker-template-action
    types: {}
  - properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: has-header-filter-action
    types: {}
  - properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: pdf-action
    types: {}
  sink:
    properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: azure-functions-sink
    types: {}
```
</details>

**Comment by lhein** [comment]
I cannot see that working for Pipes in the sandbox environment. Are you sure its working?

**Comment by lhein** [comment]
Ah I see the problem. It is because I am using a Pipe from Smart Connectors which has no equivalent for source and sink in the catalog.

**Comment by igarashitm** [comment]
@lhein yes the SCO kamelet catalog needs to be fed to show the configuration form for those. Instead you can use this Pipe to see the form.
```yaml
apiVersion: camel.apache.org/v1
  kind: Pipe
  metadata:
    name: redhat-test
  spec:
    source:
      ref:
        apiVersion: camel.apache.org/v1
        name: timer-source
        kind: Kamelet
        properties:
          period: "10000"
          message: Hello
    steps:
      - ref:
          apiVersion: camel.apache.org/v1
          name: log-action
          kind: Kamelet
          properties:
            showHeaders: "true"
    sink:
      ref:
        apiVersion: camel.apache.org/v1
        name: kafka-sink
        kind: Kamelet
        properties:
          topic: myTopic
          bootstrapServers: 192.168.0.1
          user: test2
          password: test
```
