### ISSUE TITLE
Error handler not showing error handler types in the dropdown 

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#293]
### Describe the Bug

Error handler config page doesn't show the error type selector filed names and error handler configuration fields.

used pipe:
```
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: webhook-binding
  annotations:
    sco1237896.github.com/catalog.group: "messaging"
    sco1237896.github.com/catalog.id: "http"
    sco1237896.github.com/connector.description: "Send data to a HTTP endpoint."
    sco1237896.github.com/connector.group: "messaging"
    sco1237896.github.com/connector.id: "http_sink_v1"
    sco1237896.github.com/connector.title: "HTTP sink"
    sco1237896.github.com/connector.version: "v1"
    trait.camel.apache.org/container.request-cpu: "0.20"
    trait.camel.apache.org/container.request-memory: "128M"
    trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
    trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-http:camel-4-1046a96"
spec:
  errorHandler:
    log:
      parameters:
        maximumRedeliveries: 3
        redeliveryDelay: 2000
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: webhook-source
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: delay-action
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
```

### Steps to Reproduce the Bug or Issue

1. create Pipe
2. try to configure error handler
3. see the selector issue and no config fields

### Screenshots or Videos

![Peek 2023-11-03 14-46](https://github.com/KaotoIO/kaoto-next/assets/4180208/d12c8d67-5442-466c-beaa-6849ed545e5d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
