### ISSUE TITLE
[BUG] Steps sometimes receive an `expression` property when it's not applicable

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#319]
Starting with the `default` route

```yaml
- route:
    from:
      uri: timer:template
      parameters:
        period: "1000"
      steps:
        - log:
            message: template message
    id: route-1073
```
notice how the `log` processor doesn't have an expression property defined, then you open the `log` processor to configure it, there's no `expression` field either
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/2521d651-e97f-4eb0-a179-ba71b2eda5f2)

but returning to the source code, it looks like an expression property gets added :thinking: 

_Originally posted by @lordrip in https://github.com/KaotoIO/kaoto-next/issues/272#issuecomment-1805474031_
