### ISSUE TITLE
Expression directly specified are ignored and cannot be modified in UI

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#332]
### Describe the Bug

Expression directly specified are ignored and cannot be modified in UI

for instance pick the route from [Camel example](https://github.com/apache/camel-examples/blob/main/main-yaml/src/main/resources/routes/my-route.yaml):
```yaml
- route:
    id: "foo"
    from:
      uri: "quartz:foo?cron={{myCron}}"
      steps:
        - to: "bean:myBean?method=hello"
        - log: "${body}"
        - to: "bean:myBean?method=bye"
        - log: "${body}"
```

### Steps to Reproduce the Bug or Issue

1. go to https://kaotoio.github.io/kaoto-next/#/code
2. open source code
3. paste
```yaml
- route:
    id: "foo"
    from:
      uri: "quartz:foo?cron={{myCron}}"
      steps:
        - to: "bean:myBean?method=hello"
        - log: "${body}"
        - to: "bean:myBean?method=bye"
        - log: "${body}"
```
4. go to design
5. select log element
--> the expression is empty and cannot be modified

### Platform

- OS: Linux
- Browser: Firefox
- Version: https://kaotoio.github.io/kaoto-next/#/code
