### ISSUE TITLE
Adding an otherwise when there is already one is overriding the existing one

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#334]
### Describe the Bug

Adding an otherwise when there is already one is overriding the existing one

### Steps to Reproduce the Bug or Issue

1. create route with a choice having an otherwise:
```yaml
- route:
    from:
      uri: timer:yaml?period=3s
      steps:
        - to:
            uri: log:yaml
            parameters:
              show-body-type: false
              show-exchange-pattern: false
            expression:
              simple: {}
        - choice:
            when:
              - id: when-2068
                simple: ${header.foo} == 1
                steps:
                  - log:
                      id: log-1371
                      message: ${body}
            otherwise:
              id: otherwise-1169
              steps:
                - log:
                    id: log-4778
                    message: ${body}
    id: route-1500
```
2. on the 3 vertical dots of the choice, choose "add special step node into choice" and choose otherwise
3. the existing otherwise is overriden and an invalid imbricated otherwise is created

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/1105127/99ef3f4f-774b-45e8-8ac7-f258bf074a2f

### Platform

- OS: Linux
- Browser: Firefox
- Version: online version
