### ISSUE TITLE
[BUG] Replacing `from` node makes icon dissapear

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#359]
### Describe the Bug

In a `Camel Route`, when replacing the `from` node with a `source` kamelet, makes the icon disappear and a `?` is displayed instead.

### Steps to Reproduce the Bug or Issue

1. Start with the following route:
```
- route:
    id: route-8888
    from:
      uri: activemq
      steps: []
      id: from-4167
      parameters: {}
```

You'll see the following:
![Screenshot from 2023-11-17 09-12-36](https://github.com/KaotoIO/kaoto-next/assets/16512618/3a6a9335-518b-4604-8af8-cff53fb2a796)

2. Replace it with the `BeerSource` kamelet and notice how the icon is now a `?` (question mark)
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/95ecc646-2ff0-4ded-a7a7-d7ca5d8f783d)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.2.0]
