### ISSUE TITLE
Nodes can't be configured when the `parameters` property is `null`

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#393]
### Describe the Bug

When the `parameters` property is mistakenly set to `null`, the node can't be configured using the right side panel.

### Steps to Reproduce the Bug or Issue

Using the following route:
```
- route:
    from:
      uri: timer
      steps: []
      id: from-9879
      parameters: null
    id: route-3021
```

try to configure the `timer` component and notice that only the `URI`, `Id`, and `Description` properties can be configured. this is because those properties belong to the `from` EIP

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
