### ISSUE TITLE
 Error opening `Filter` step configuration

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#395]
### Describe the Bug

`filter` can't be configured

### Steps to Reproduce the Bug or Issue

1. Use the following route:
```yaml
- route:
    from:
      uri: timer
      steps:
        - filter: {}
      id: from-9879
      parameters: null
    id: route-3021
```
2. Click on the `filter` node and see how the configuration form is not available.

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/57f3ecbd-8094-4b2f-8f21-654a817f2098)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
