### ISSUE TITLE
Source kamelets are added without the `kamelet` prefix

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#409]
### Describe the Bug

When replacing a `from` node in a Camel Route, the `URI` is missing the `kamelet:` prefix.

### Steps to Reproduce the Bug or Issue

1. Use the following route:
```yaml
- route:
    from:
      uri: timer
      parameters: {}
      steps:
        - log:
            message: template message
      id: from-3242
    id: kamelet-source
```
2. Replace the `timer` node with a source Kamelet like `cron`
3. Notice how the `cron` node doesn't have an icon nor can be configured.

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/b69b1b3d-0c02-4dd5-9f6f-d4a54dc8ca3d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
