### ISSUE TITLE
Short form avro dataformat is not correctly parsed

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#439]
### Describe the Bug

When `avro` dataformat is specified with a string like following, it should be used as a `instanceClassName` property
```yaml
- route:
    from:
      uri: timer:test
      steps:
        - marshal:
            avro: org.apache.avro.ipc.MD5

```
equivalent to
```yaml
- route:
    from:
      uri: timer:test
      steps:
        - marshal:
            avro:
              instanceClassName: org.apache.avro.ipc.MD5

```

currently it is just ignored.

### Steps to Reproduce the Bug or Issue

1. Paste the upper YAML code
2. See marshal step form

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
