### ISSUE TITLE
Use verbose dialect for default expression

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#475]
### Please describe the task that needs to be done

Here the default `when` expression uses short version of dialect
https://github.com/KaotoIO/kaoto-next/blob/main/packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts#L73

```yaml
          when:
          - id: ${getCamelRandomId('when')}
            simple: "${header.foo} == 1"
```

But it soon is converted to the most verbose dialect once the condition is modified
```yaml
          when:
          - id: ${getCamelRandomId('when')}
            expression:
              simple:
                expression:  "${header.foo} == 1"
```

It would be better to use the latter from beginning so that the kaoto generated expression is always aligned.
