### ISSUE TITLE
Config panel for Direct element from a route generated from jbang and OpenAPI is not loading

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#500]
### Describe the Bug

Config panel for Direct element from a route generated from jbang and OpenAPI is not loading

the content of the file is:
```yaml
- rest:
    path: "/v1"
    get:
    - id: "listPets"
      path: "/pets"
      produces: "application/json"
      param:
      - dataType: "integer"
        description: "How many items to return at one time (max 100)"
        name: "limit"
        required: false
        type: "query"
      to: "direct:listPets"
    - id: "showPetById"
      path: "/pets/{petId}"
      produces: "application/json"
      param:
      - dataType: "string"
        description: "The id of the pet to retrieve"
        name: "petId"
        required: true
        type: "path"
      to: "direct:showPetById"
    post:
    - id: "createPets"
      path: "/pets"
      produces: "application/json"
      to: "direct:createPets"
- route:
    from:
      uri: "direct:showPetById"
- route:
    from:
      uri: "direct:listPets"
- route:
    from:
      uri: "direct:createPets"
```

there is this error in the console log:
```
react-dom.production.min.js:189 TypeError: t.toJSON is not a function
    at camel-route-resource.ts:55:49
    at Array.map (<anonymous>)
    at eL.toJSON (camel-route-resource.ts:55:26)
    at yo (createNode.js:56:27)
    at To.createNode (Document.js:138:22)
    at new To (Document.js:53:47)
    at EN (public-api.js:96:12)
    at Object.updateSourceCodeFromEntities (entities.ts:60:18)
    at w.useCallback.g [as onChangeModel] (CanvasForm.tsx:44:24)
    at t.<anonymous> (AutoForm.js:32:32)
```

### Steps to Reproduce the Bug or Issue

1. Generate a Camel route from Jbang, with something like:
`jbang '-Dcamel.jbang.version=4.2.0' camel@apache/camel generate rest --input=/home/apupier/Downloads/petstore.json --output=RestOne.camel.yaml --routes`

petstore is coming from https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.json
2. Open the generated route
3. Select the Direct element

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/f96cce3b-ff24-473e-b364-b97a774c1979)

### Platform

online version
