### ISSUE TITLE
Missing expression editor for `setHeaders` EIP

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#577]
### Please describe the feature that you want to propose

`setHeaders` has simply an array of `SetHeaderDefinition`, and with current auto field it doesn't render expression editor for each header
![Screenshot from 2023-12-19 10-19-49](https://github.com/KaotoIO/kaoto-next/assets/265462/48c50de0-0c57-435a-bff2-95f56237aec3)

It might be better to address this together with #523 

#### Update
Because of the short form of expressions spreading into the top node such as
```yaml
 - setHeaders:
     headers:
     - name: header1
       simple: '${body}'
     - name: header2
       jq: '.field1'
```
We need to consume whole `setHeader` node, i.e. `/setHeaders/header[n]` to parse the expression. Unlike #523 where the expression spreads into the top node of the step object, this `setHeaders` has such structure in the middle of the main config. We need a way to nest the uniforms instance through some custom field.
