### ISSUE TITLE
Properties for Pipes are placed at the wrong level

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#653]
### Describe the Bug

Despite a property specified in source code, the message is not displayed in the config form

### Steps to Reproduce the Bug or Issue

1. Load for instance the example from https://github.com/apache/camel-kamelets-examples/blob/030729ee7e32cb01e5388783b8cf81b8b1a0ee78/jbang/camelk-bind/my-bind.yaml
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: my-bind
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      message: "hello world"

  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    #properties:
      #key: "value"
 ```
 2. select timer-source
 --> the message field is empty

### Platform

Kaoto online
