### ISSUE TITLE
Wrong parsing of Camel uri when a path parameter is not required and not provided

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#654]
### Describe the Bug

Destinationname of jms example is not displayed in config form

### Steps to Reproduce the Bug or Issue

1. Load xample from https://github.com/apache/camel-kamelets-examples/blob/030729ee7e32cb01e5388783b8cf81b8b1a0ee78/jbang/artemis/consumer.yaml : 
```yaml
# camel-k: language=yaml

# Write your routes here, for example:
- from:
    uri: "jms:cheese"
    steps:
      - log: "${body}"
```
2. Select jms
3. Notice that destinationname is empty although it shoudl contain `cheese`

### Platform

Kaoto online

**Comment by apupier** [comment]
when providing a vbalue for the destinationName, we can notice that the destinationName was mistaken with the destinationType:

```yaml
- route:
    id: route-1658
    from:
      uri: jms
      parameters:
        destinationName: providedFromUI
        destinationType: cheese
      steps:
        - log: ${body}
```
