### ISSUE TITLE
Component of type kamelet are not recognized when they have parameters within uri

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#657]
### Describe the Bug

Component of type kamelet are not recognized when they have parameters within uri

### Steps to Reproduce the Bug or Issue

1. Load from https://github.com/apache/camel-kamelets-examples/blob/6351ea42401452ec7bf8897d4c5a2f49478e0e83/jbang/kafka-health/producer.yaml
```yaml
- route:
    id: route-7827
    from:
      uri: kamelet:chuck-norris-source
      steps:
        - log: ${body}
        - to:
            description: azz
            uri: kamelet:kafka-not-secured-sink?topic=foobar&bootstrapServers=localhost
            parameters: {}
```
2. the kamelet step is marked as unrecognized

removing the parameters o the URi is working, so using something like:
```yaml
- route:
    id: route-7827
    from:
      uri: kamelet:chuck-norris-source
      steps:
        - log: ${body}
        - to:
            description: azz
            uri: kamelet:kafka-not-secured-sink
            parameters: {}
```

### Platform

Kaoto online
