### ISSUE TITLE
Required properties validation not showing missing properties in Pipes prior to edit

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#698]
### Describe the Bug

The Pipe type route resources are not displaying the missing properties warnings prior to editing of the node properties.

e.g. the warnings, there are missing properties are not displayed on pipe import, or when adding new node with mandatory properties:

(pipe for import)
```
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: pipe-1640
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: cassandra-source
  sink:
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: kafka-sink
```

### Steps to Reproduce the Bug or Issue

1. import the provided pipe
2. see the warnings are not displayed

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/4180208/54b8def1-15bb-4b6f-8956-a6ee749c7b4e

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
