### ISSUE TITLE
`setHeaders` processor is broken

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#727]
### Describe the Bug

After merging https://github.com/KaotoIO/kaoto-next/pull/726, the `setHeaders` processor is broken due to the change in the `AutoForm` mechanism.

### Steps to Reproduce the Bug or Issue

1. Add a `setHeaders` processor
2. Edit a header
3. Notice how the structure is not correct
```yaml
        - setHeaders:
            id: setHeaders-2000
            description: hola
            headers:
              - null
            headers.0:
              expression:
                simple:
                  expression: myExpression
              name: myName
            headers.0.name: myName
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
