### ISSUE TITLE
Support Knative resource references in Pipe

### ISSUE THREAD

**Issue by christophd** [KaotoIO/kaoto-next#843]
### Please describe the feature that you want to propose

Pipes are able to directly reference Knative resources (e.g. broker, channel) as a source or sink in a Pipe.

Example
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: timer-to-knative-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      period: 5000
      contentType: application/json
      message: |
        { "client": "timer-pipe", "message": "Hello from timer-pipe!" }
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default
    properties:
      type: org.apache.camel.event.messages
```

Kaoto designer should be able to display the Knative resource reference and its properties as if it were a Kamelet.

Example Knative channel reference:

```yaml
...
  sink:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1
      name: messages
```
