### ISSUE TITLE
Default values are not shown in the Form

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#906]
### Describe the Bug

Default values are not shown in the Canvas Form.

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/0ceb015a-64fa-4d51-89fe-00d69f1f74f6)

### Steps to Reproduce the Bug or Issue

Using the following YAML schema:

```yaml
- route:
    from:
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - aggregate:
            id: aggregate-1904
```

Notice how the default value of the `completionTimeoutCheckerInterval` property is not shown, despite being available [in the Camel Catalog](https://github.com/apache/camel/blob/4037b417b75e791bff0b9da04538cfff4f297b62/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/aggregate.json#L34C14-L35C1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
